"""add documents info storing

Revision ID: cb5908f69710
Revises: 0faa20e87e40
Create Date: 2025-06-13 16:02:45.542117+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb5908f69710'
down_revision: Union[str, None] = '0faa20e87e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_message_fk_key'), 'documents', type_='unique')
    op.create_unique_constraint(None, 'documents', ['telegram_file_id'])
    op.drop_column('documents', 'document_received_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_unique_constraint(op.f('documents_message_fk_key'), 'documents', ['message_fk'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
