"""removed summary_id from messages

Revision ID: 2597847f8a5c
Revises: cb5908f69710
Create Date: 2025-06-13 17:07:58.500232+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2597847f8a5c'
down_revision: Union[str, None] = 'cb5908f69710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_summary_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'summary_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('summary_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_summary_id_fkey'), 'messages', 'summaries', ['summary_id'], ['id'])
    # ### end Alembic commands ###
